import 'src/config/database'
import 'src/config/langs'

import 'src/functions/sapling'
import 'src/functions/func'
import 'src/functions/static'

import 'src/commands/sapling'
import 'src/commands/func'
import 'src/commands/camera'
import 'src/commands/help'
import 'src/commands/fakeplayer'
import 'src/commands/prof'
import 'src/commands/calc'
import 'src/commands/hss'
import 'src/commands/config'